import { useState } from "react";
import { signIn } from "../services/supabase";
import { Link, useNavigate } from "react-router-dom";
import { Button, Form, Container, Row, Col, Card } from "react-bootstrap";
import { toast } from "react-toastify";

/**
 * LoginPage component.
 * Allows users to login to their account.
 *
 * @return {JSX.Element} - The JSX element representing the LoginPage component.
 */
export default function LoginPage() {
	const [email, setEmail] = useState(""); // State to hold the email input
	const [password, setPassword] = useState(""); // State to hold the password input
	const navigate = useNavigate(); // Hook to navigate to different pages

	/**
	 * Handles the login form submission.
	 * Validates the input fields and attempts to sign in the user using the Supabase client
	 *
	 * If successful, displays a success toast and navigates to the HomePage.
	 *
	 * @param e event generated by the form submission
	 */
	const handleLogin = async (e: React.FormEvent) => {
		e.preventDefault();

		// Validates input
		if (!email || !password) {
			toast.error("Tutti i campi sono obbligatori.");
			return;
		}
		if (!email.includes("@") || !email.includes(".")) {
			toast.error("Inserisci un indirizzo email valido.");
			return;
		}

		try {
			const { user: userData } = await signIn(email, password); // Signin using Supabase client

			toast.success("Benvenuto " + userData.user_metadata.username, {
				autoClose: 2000,
			});
			navigate("/HomePage"); // Navigate to HomePage on successful login
		} catch (error: any) {
			toast.error("Errore durante il login!");
			console.error(error);
		}
	};

	// Render the login form
	return (
		<Container className="mt-5">
			<Row className="justify-content-center">
				<Col md={4}>
					<Card className="form-card">
						<Card.Body>
							<h3 className="text-center mb-4">Login to your account</h3>
							<Form onSubmit={handleLogin}>
								<Form.Group className="mb-4" controlId="email">
									{/* <Form.Label>Email</Form.Label> */}
									<Form.Control
										type="email"
										value={email}
										onChange={(e) => setEmail(e.target.value)}
										placeholder="Inserisci la tua email"
										required
									/>
								</Form.Group>
								<Form.Group className="mb-4" controlId="password">
									{/* <Form.Label>Password</Form.Label> */}
									<Form.Control
										type="password"
										value={password}
										onChange={(e) => setPassword(e.target.value)}
										placeholder="Inserisci la tua password"
										required
									/>
								</Form.Group>
								<Button variant="primary" type="submit" className="w-100">
									Login
								</Button>
								<p className="text-center mt-3">
									Non hai un account? <Link to="/SignupPage">Registrati</Link>
								</p>
							</Form>
						</Card.Body>
					</Card>
				</Col>
			</Row>
		</Container>
	);
}
